### PR TITLE
Frmdstryr add binder

### PR DESCRIPTION
**Pull request by trelau**

### CODE REVIEW

**Comment by trelau** [comment]
@frmdstryr made this branch/PR off yours. trying to resolve some errors. might work it locally for a bit...

**Comment by trelau** [comment]
hmm...still looking for windows.h on the linux build, but likely because something needs defined during the binder process. in the file it references, it's this:

image

i think the +arg from the config.txt will need to made platform specific. so either some kind of specifier like "+arg win: arg" or "+arg linux: arg" or "+arg osx: arg". and then account for the in the binder with sys.platform check.

**Comment by frmdstryr** [comment]
Agree, not sure how I missed those `ms-` flags...  anyways looks like its going well so far!

**Comment by trelau** [comment]
"the compiler is out of heap space" 🙄

**Comment by trelau** [comment]
@frmdstryr any guess on this for linux build? https://laughlinresearch.visualstudio.com/pyOCCT/_build/results?buildId=60&view=logs&j=5c582689-28ec-52cb-37f1-b34f7eb55eb9&t=dc1238ff-8676-59ce-1364-1e26e1555bb3&l=606

**Comment by frmdstryr** [comment]
To fix the linux build:

```
+patch bind_BOPTools_PairSelector: std::vector<PairIDs>-->std::vector<typename BOPTools_PairSelector<Dimension>::PairIDs>
```

**Comment by frmdstryr** [comment]
I'm not sure why pybind is picking up the wrong python... 

From looking at https://github.com/pybind/pybind11/blob/master/tools/pybind11Tools.cmake#L16 I guess `PYBIND11_PYTHON_VERSION` needs passed to cmake?

**Comment by trelau** [comment]
@frmdstryr hmm ya i just noticed that. a bit surprised. i did add some platform specific compiler arguments to the binder. not sure i got them all, but did seem to get rid of the missing include files. tho getting some others type issue in OSD_WNT (which maybe shouldn't be part of linux build anyway?).

**Comment by trelau** [comment]
looking at the OCCT source build files, maybe the definitions and compiler arguments should more closely match?

**Comment by frmdstryr** [comment]
After merging the build and host into sections one, re-adding smesh, and changing it to clone the pyOCCT_binder repo it looks like "it's working" on github-actions so maybe it's something with the vm images used by azure?

https://github.com/frmdstryr/pyOCCT/actions/runs/89168393

**Comment by frmdstryr** [comment]
Got fonts working (though a bit of a hack)

declaracad-text

**Comment by frmdstryr** [comment]
Not sure if you saw https://github.com/frmdstryr/pyOCCT/tree/github-actions hopefully something there helps.

Something seems to be broken with conda, I had to add the python version into the variant file and pass the flag from ci for it to use the correct python version. Its building ok on both win & linux using the binder repo now in that branch

**Comment by trelau** [comment]
ya i'm frustrated and trying github actions now...

just hacking away at stuff. trying to figure out how to trigger an action now...

**Comment by trelau** [comment]
@frmdstryr i'm a bit stumped. it gets all the way then this happens...

https://github.com/LaughlinResearch/pyOCCT/pull/37/checks?check_run_id=633254067#step:8:8877

**Comment by frmdstryr** [comment]
Yeah something seems to be screwed up with conda because it installs it into the build env instead of the host env

Eg from the log:
```
Installed $BUILD_PREFIX/lib/python3.6/site-packages/OCCT-7.4.0.0-py3.6.egg
```

https://github.com/LaughlinResearch/pyOCCT/runs/634973555#step:8:689

To workaround that I had to pass the prefix explicitly in build.sh and bld.bat (https://github.com/LaughlinResearch/pyOCCT/compare/master...frmdstryr:github-actions#diff-a1f81322d0afba052bd6bd2e49b3877cR21)

**Comment by trelau** [comment]
haha wow...linux ran, then i changed something only for windows build and it then worked, but linux failed because it picked up the wrong python library again...what the hell...

**Comment by frmdstryr** [comment]
I had to add python in the variant config and pass the version in the build command for conda to install the correct version... 

https://github.com/frmdstryr/pyOCCT/blob/github-actions/ci/conda/conda_build_config.yaml#L4-L7 
https://github.com/frmdstryr/pyOCCT/blob/github-actions/.github/workflows/ci.yml#L48

**Comment by frmdstryr** [comment]
Does ray tracing work for you on windows? If I use the https://www.opencascade.com/content/cad-assistant app it works but the opengl driver says it's not supported when trying to use it from pyocct.

**Comment by trelau** [comment]
> Does ray tracing work for you on windows? If I use the https://www.opencascade.com/content/cad-assistant app it works but the opengl driver says it's not supported when trying to use it from pyocct.

i haven't tried this. if you can isolate, would make a good unit test to at least isolate the issue, and once fixed, make sure it stays fixed. maybe once this basic CI stuff starts working...

**Pull request merged**
