### PR TITLE
Add binder

### PR DESCRIPTION
**Pull request by frmdstryr**
Rebased on azure_support again

### CODE REVIEW

**Comment by frmdstryr** [comment]
Uhh.. I don't have a windows system to test on: 

```
ERROR: OpenCASCADE include path does not exist:None
```

It seems none of these env vars are working on windows https://github.com/LaughlinResearch/pyOCCT_binder/blob/master/generate/run.py#L19 any ideas?

**Comment by trelau** [comment]
A few things after quick glance. Here is the path to opencascade headers on my local conda environemnt

`C:\Miniconda\envs\occt740\Library\include\opencascade`

I think in the linux build it shows this in the pipeline

`/usr/share/miniconda/envs/pyOCCT/include/opencascade`

there is an extra "Library" there in the middle, but my guess is that should be picked up by the env variables, so may have to test locally or dump out the env variables to see their paths for debugging

also noticed this in the linux pipeline (and probably windows)
image

i remember i had to manually copy this file from 7.3.0 to 7.4.0 headers to get things to parse, bind, and compile. not sure why that file is missing in occt 7.4.0 distribution? that may also be throwing the parser off. i think in the past when it hit stuff like that it'd stop parson and/or not fully complete assembling the definitions, and i remember seeing things like `int` showing up, which it looks like you have patches for. might not be related, but just fyi. if we have to, could maybe add the include file locally to pyOCCT project somewhere and add an include path for the binder?

**Comment by frmdstryr** [comment]
Can you retrigger the windows build (if possible)?  

Also it should be uploading the generated src but I'm not sure where they can be downloaded (https://laughlinresearch.visualstudio.com/pyOCCT/_build/results?buildId=50&view=logs&j=5c582689-28ec-52cb-37f1-b34f7eb55eb9&t=a2aba3aa-55dc-5c7d-339c-f4855ae16ebb&l=18).

**Comment by trelau** [comment]
yes i'm trying to trigger the windows build but it seems stuck in a queue or something. also, the artifacts are here for one of the build https://laughlinresearch.visualstudio.com/pyOCCT/_build/results?buildId=50&view=artifacts&type=publishedArtifacts

there is a summary screen for each build that i think has a link to any artifacts. also i think since it puts all the artifacts in a single place for a pipeline (including all the builds), we'll eventually need to have unique names for artifacts lke "pyocct_src_ubuntu_18_04" or "pyocct_src_vs2017", but can address that once things get working

**Comment by frmdstryr** [comment]
Looks like it's building for the wrong version of python too... `    python:           3.8.2-he5300dc_7_cpython   conda-forge`

**Comment by frmdstryr** [comment]
Any ideas on why that could happen? 

https://laughlinresearch.visualstudio.com/pyOCCT/_build/results?buildId=51&view=logs&j=c4f15b30-8990-5ceb-2e12-e8710b6542b6&t=3151abd1-c972-539f-f99e-7275e7172688&l=541

I vaguely remember seeing it once before but don't remember what fixed it...

**Comment by trelau** [comment]
ya it's an assert that "should" never happen, but is a result of apparently not being able to find a robust way to get all the base classes of a type https://github.com/LaughlinResearch/pyOCCT_binder/blob/a6fe63d7f5bef2c3f5f5c4fbf1269a5a9a8cb4e3/binder/core.py#L1632 which is the reason for all the logic and different attempts of getting base classes in that chunk of code above the assert...

**Comment by trelau** [comment]
hmmm i don't hit the assert locally...

**Comment by frmdstryr** [comment]
Only thing I can think of is that some includes are missing?

**Comment by trelau** [comment]
yes includes are missing, not sure if fixing will help the assert, but...

after adding include paths for the missing AIS file, VTK, and tbb i noticed that the only patch needed is some vtk related, stuff, no more "int", which if i remember correctly, was because the parser (clang) gets tripped up if any missing includes are present. i noticed this when i added the AIS file, the next time i ran it i saw a missing include error for vtk, then added that, then saw one for tbb, added that was the last one.

here is the only patched files after this
image

and here is the local hack i did to test (adding some more include paths)
image

one thing we can do is store that missing AIS file in this project for now, but eventually move it to pyOCCT

**Comment by trelau** [comment]
i'll go work on the binder and make a PR

**Comment by frmdstryr** [comment]
Sounds good. I'm thinking it might also help debugging if the log.txt the binder generates it printed out if there's an error.

**Comment by trelau** [comment]
may also need to add `tbb-devel` in meta.yaml so it can find the header files and such during binding generation. it's available from conda-forge

**Comment by trelau** [comment]
oops i may have made it worse with the recent binder changes...

**Comment by trelau** [comment]
hmm..ok....perhaps time for me to slow down and make the include paths more robust...was hoping to get it working quickly and cleanup later...but...

**Comment by trelau** [comment]
so strange it's still hitting that assert on windows...but doesn't locally...

**Comment by trelau** [comment]
hmm not sure if i did something, but saw this during the binder run in linux pipeline?
image

**Comment by trelau** [comment]
ya i bet these need configured per platform https://github.com/LaughlinResearch/pyOCCT_binder/blob/b4f1ff304289bc3fbe4e6e569182664ad9e2fcc8/generate/config.txt#L3

**Comment by frmdstryr** [comment]
Yeah, getting that locally now too, it seems to be picking up files from conda's package cache (the pkg folders)?

Also I think the `src/occt/` folder needs cleaned out before running the binder.

**Comment by trelau** [comment]
didn't seem to have as many problems when the binder was part of conda-build, should we revert back to that? does that help with setting some of the definitions before running the binder?

**Comment by trelau** [comment]
and yes might as well delete the src/occt files from the project since those are generated (keeping src/smesh).

**Comment by frmdstryr** [comment]
It's worth a try, I'm still not sure why it doesn't work though since in both cases it's activating an env.

**Comment by trelau** [comment]
i think conda-build adds a lot more to the path and system than just activating a conda environment. also wondering, it seems like we need to only run the binder once for win, osx, and linux, and then just reuse the sources or even intermediate files to link to different versions of python (3.5, 3.6, 3.7, 3.8).

**Comment by frmdstryr** [comment]
Should we reopen #33 ? I think that just needs to add `-j2` to `blt.bat` so it doesn't run out of memory

**Comment by trelau** [comment]
ya let's give it a shot

**Comment by trelau** [comment]
hmm...may be easier to refactor this PR a bit. remove the src/occt from the repo. then add in cloning the binder in pipeline, but call it during conda build

**Comment by frmdstryr** [comment]
I think you should be able to push commits to this branch, might make it move a little faster

**Comment by trelau** [comment]
yup i'm setting that up now 👍

**Comment by frmdstryr** [comment]
Continued in #37

**Pull request closed without merging**
