### PR TITLE
Occt 7.3.0 linux

### PR DESCRIPTION
**Pull request by frmdstryr**
This fixes the build on linux by:
1. Adding `typename` where required
2. Adding the `-fpermissive` flag to allow casting function pointers
3. Disabling the delete operator on the NCollection/Poly types which use a custom allocator
4. Pulling in xType/XwWindow changes from master
5. Removing any undefined symbols
6. Adding a constructor to BRep_Builder
7. Adding the Qt viewer from https://github.com/LaughlinResearch/pyOCCT/pull/20 (using [qtpy](https://github.com/spyder-ide/qtpy))

It also adds linux testing to appveyor, updates the travis build to use bionic, and makes linux use g++-9 as the compiler.

## Description
Fixes 7.3.0 build on linux

## Motivation and Context
The 7.3.0 linux build is failing

## How Has This Been Tested?

Built on ubuntu 18.04 with Python 3.7 and manually tested by running the examples.

## Screenshots (if appropriate):

occt-7 3 0-linux

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by trelau** [comment]
thanks for the PR...haven't had a chance to look at it...but until then...you might consider adding relevant changes to the binding generator https://github.com/LaughlinResearch/pyOCCT_binder

The goal, I think, would be to capture as much of the binding generation rules in that tool, and only do manual edits perhaps in between major OCCT updates as necessary (while still capturing those in the binding generator if possible)

for this occt_730 branch, the files so far are completely generated by the binding generator...so..i'm a bit nervous about merging changes if not captured either in the binding generator of with clear tests if manual patches are needed

again...i still need to review and find some time to work on this again...but in case you want to contribute to that tool...would be a great contribution

**Comment by frmdstryr** [comment]
If the goal is full automation would it make sense to include the binder in this repo so it could be run with ci? 

The changes for adding typename and nodelete should be easy to add to the binder, however I'm unsure how the binder handles the preprocessor defs.  If the binder is run on the correct platform hopefully that'd fix the undefined symbols (I didn't try running it)..

**Comment by trelau** [comment]
hmm...moving the binder to this repo is interesting...not sure i know enough yet to know if that's a good idea...for now...it's close to getting 7.3.0...so i'm tempted to keep them separate...get an initial 7.3.0 release out...then reconsider....also OCCT 7.4.0 is out so may get caught up to that

i'd also like to redo the way i do the SMESH repo...so all of that might be part of a larger project worth considering

**Comment by frmdstryr** [comment]
Makes sense, yes it would be good to also have 7.4.0, interested to see how much (if anything) needs changed.  

Also I'm not sure why it's failing due to out of memory errors...

**Comment by frmdstryr** [comment]
Well the appveyor build finally worked,  I'm not sure what's up with travis.  

I tried running the binder locally and it seems to properly handle preprocessor statements so running binder on CI should address the platform specific issues, but not the undefined symbols... 

I gave it a quick run on 7.4.0 but hit a bunch of errors when compiling so it'll need some more tuning.

**Comment by trelau** [comment]
ok cool...i remember in the past i had to split up large source files since the memory available on the CI machines is pretty limited...so the AIS package was one...but i remember that on AppVeyor but not linux

i'm not surprised it didn't work for 7.4.0...there are still a lot of manual patches to be captured for each release...

for now...let's see try and get a 7.3.0 success...then perhaps turn towards how best to do the binder generation and capture different platforms

**Pull request closed without merging**
