### PR TITLE
Return policy update

### PR DESCRIPTION
**Pull request by trelau**
Use `py::return_value_policy::reference` for anything that returns a non-const lvalue

### CODE REVIEW

**Comment by trelau** [comment]
@frmdstryr fyi. things seem to build and test ok. let me know if you spot anything weird or test out the binaries locally and spot anything.

I think i would like to make an official 7.4.0.0 release and get it up on conda. anything you'd want in before i cut that release?

**Comment by trelau** [comment]
@frmdstryr are you able to reproduce this locally? https://github.com/LaughlinResearch/pyOCCT/runs/683084954?check_suite_focus=true#step:7:8011

i couldn't reproduce it locally, but seems to fail in the workflow. i might try another branch before the return value policy update?

**Comment by frmdstryr** [comment]
Hmm, yes. I'm getting the same error locally.

**Comment by frmdstryr** [comment]
Maybe deleting the reference is deleting the object? 

If I comment out the `test_Shell` then it works, also strangely, if I rename `test_Shell` so it runs after `test_Solid` it also works

**Comment by frmdstryr** [comment]
Doh... after re-reading https://pybind11.readthedocs.io/en/stable/advanced/functions.html?highlight=return_value_policy#return-value-policies maybe it should be using `return_value_policy::reference_internal` ?

**Comment by trelau** [comment]
@frmdstryr perhaps. at this point, what do you think about going back to no assumed return policy? and just start by case by case basis with the config.txt until we learn more about the implementation details? I can try instead using reference_internal if you think it's worth a shot

**Comment by trelau** [comment]
and yes, it only seems to be happening after getting the Solid after the Shell. I cannot reproduce it any other way. i might try a small c++ test to see if i can reproduce it in the native code.

**Comment by frmdstryr** [comment]
I changed it locally to use `reference_internal` and all the tests are passing.

**Comment by frmdstryr** [comment]
Oh... I forgot to revert my rename, so no wonder it passed locally. 

Probably need to just revert this and manually add special cases to the config...

**Comment by trelau** [comment]
oh ya for now we'll just do a manual thing via the config file until we can nail down some rules for when to apply different return value policies

**Comment by trelau** [comment]
@frmdstryr this is strange. the test is failing, even tho i reverted back any return policy changes. I built a cpp and python test locally it I can't reproduce it. Attached is a standalone project that I was usually to try and reproduce locally. Maybe you can reproduce it?

[test.zip](https://github.com/LaughlinResearch/pyOCCT/files/4671820/test.zip)

**Comment by frmdstryr** [comment]
Isn't that test new? Maybe it was always failing?

**Comment by trelau** [comment]
that's what i thought at first, but i first notice it causing a failure [here ](https://github.com/LaughlinResearch/AFEM/blob/b4ee5b10ffc1155bc5a131d0106edfc92ccec46b/test/test_topology.py#L253)in a different project.

Then I added this test to pyOCCT and saw the failure. But then, I tried to reproduce locally in C++ and Python (that is the small file I attached) and could not. Now I just build pyOCCT locally using CMake (i.e., not conda build) and the test passed fine. I'm building locally with conda build right now and going to try those binaries in the test.

**Comment by trelau** [comment]
hmm..so, locally i had installed occt 7.4.0 h823b557_1. When i updated occt locally to h823b557_6, the test fails locally with both the bindings i built locally and those downloaded from actions. so now trying to specify version h823b557_1 directly in meta.yaml. if that works, that is strange. i wonder what has changed?

@looooo you have been updating the conda-forge occt repo, anything come to mind? (see above thread if you're interested, if not nbd)

**Comment by trelau** [comment]
with occt updated locally, this test program crashes in cpp

``` cpp
#include <iostream>

#include <BRepPrimAPI_MakeBox.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Solid.hxx>
#include <TopoDS_Shell.hxx>


int main()
{

	BRepPrimAPI_MakeBox builder = BRepPrimAPI_MakeBox(10, 10, 10);

	// Put this line here and is works
	// const TopoDS_Solid& solid = builder.Solid();
	
	const TopoDS_Shell& shell = builder.Shell();
	
	// Put this line here and program crashes
	const TopoDS_Solid& solid = builder.Solid();

	std::cout << "Made it here\n";

}
```

will probably file an issue in occt-feedstock

**Pull request merged**
