### PR TITLE
Use PySide2 as GUI toolkit

### PR DESCRIPTION
**Pull request by ffvpor**
## Description

As discussed in #18 this pull propose to change from wxpython to PySide2 in OCCT/Visualization
I use pyside code from commit 48018d2c41

- Change initialization order, as suggested by @jf---
- Complete key mapping for view orientation (numbers 0 to 6, like Freecad)

 ## Be indulgent

It's my first pull request!

### CODE REVIEW

**Comment by trelau** [comment]
Thanks @ffvpor. you might need to remove `wxpython` and replace with the conda-forge pyside2 in the `meta.yaml`:

https://github.com/LaughlinResearch/pyOCCT/blob/master/ci/conda/meta.yaml#L28

https://anaconda.org/conda-forge/pyside2

**Comment by trelau** [comment]
@ffvpor would it be possible to make a new module for this pyside2 based viewer? like add a `OCCT.Visualization.PySide2.py` or something? I'd like to have a chance to test it out and migrate some other projects over to it before I commit fully to it.

Also, I'm not entirely sure about the licensing terms since it's based on Qt (GPL? LGPL?). Not an expert here, just another reason to make it in an optional module perhaps, at least in the short-term. It's just not clear to me yet, need to think more about it.

**Comment by jf---** [comment]
Qt is both LGPL and commercially licensed. PyQt has similarly a commercial and IIRC GPL rather than LGPL licensed code. PySide2 is the supported python wrapper by the Qt company. Rather than supporting ( PyQt4 / 5, PySide, PySide2 ) I'd recommend supporting PySide2 only. Since it draws out a clear dependency choice.

There is a well supported shim library, that paves out some of the differences. That works to some extent. This script is small enough that `Qt.py` might be a good idea. That said, when creating larger projects, you'd want explicit dependencies. Since you do not need historically to support a multitude of Qt backends, IMO its best not to do so.

**Comment by trelau** [comment]
@jf--- thanks for info. Definitely do not want to support multiple GUI frameworks. I was just suggesting to put it in a separate mod for now so it can be tested and migrated as main UI when ready. I have some projects using pyOCCT that are nearing delivery and I don't want to disrupt things too much.

Just to be clear, is PySide2 and its dependencies LGPL compatible? For some reason I find myself hesitant to use any GPL based dependencies (if there are any).

**Comment by trelau** [comment]
In master branch both wx and a Qt based viewer are available. Closing this PR out but welcome any news ones!

**Pull request closed without merging**
